version: 2.1
jobs:
  run:
   docker:
      - image: hdrjt/aosp:latest
   resource_class: medium

   steps:
      - run:
          command: |
           echo 'success'

workflows:
  version: 2.1
  cooking:
    jobs:
      - run
